baseURL = "https://www.anttikivi.com/"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
enableMissingTranslationPlaceholders = true
languageCode = "en-GB"
title = "Antti Kivi"

[params]
  description = "MISSING"
  opengraphImageAlt = "MISSING"
  [params.languageMenu]
    en-GB = "in English"
    fi = "suomeksi"

[languages]
  [languages.en]
    languageCode = "en-GB"
    languageName = "English"
    weight = 1
    [languages.en.params]
      description = "Antti Kivi, Finnish software developer. On this site, I’ll share my open‑source projects and writings."
      opengraphImageAlt = "Big text saying 'Antti Kivi' and a smiling face with the letters A and K as its eyes"
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "about"
        pageRef = "/about"
        weight = 1

  [languages.fi]
    languageCode = "fi"
    languageName = "Suomi"
    weight = 2
    [languages.fi.params]
      description = "Antti Kivi, ohjelmistokehittäjä. Tällä sivustolla jaan projektejani ja kirjoituksiani."
      opengraphImageAlt = 'Suuri teksti, jossa lukee "Antti Kivi", ja hymyilevät kasvot, jonka silminä on A- ja K-kirjaimet'
    [languages.fi.menus]
      [[languages.fi.menus.main]]
        name = "minusta"
        pageRef = "/about"
        weight = 1
