baseURL = "https://www.anttikivi.com/"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "term"]
languageCode = "en-GB"
title = "Antti Kivi"

[languages]
  [languages.en]
    languageCode = "en-GB"
    languageName = "English"
    weight = 1
  [languages.fi]
    languageCode = "fi"
    languageName = "Suomi"
    weight = 2
